main: com.prox.integration.Main
name: ProxIntegration
version: 1.0
author: jtsalisbury
description: Provides integration with Prox
api-version: 1.16
commands:
  settoken:
    description: Set the Prox authorization tokens
    usage: /settoken [token]
    permission: prox.manage
    permission-message: You don't have the prox.manage permission.
permissions:
  prox.manage:
    description: Allows for management of Prox
    default: op